### ISSUE TITLE
Remote deploy of a marvin engine package

### ISSUE THREAD

**Issue by takabayashi** [marvin-ai/marvin-python-toolbox#1]
Design and build a shell script to deploy on a remote machine (Eg. ec2, azure and google cloud) a marvin package.

Following this steps..

Package in a popular format (Eg. Docker)
Flexible remote machine credential and location configuration
Deploy de package on the machine and return success or fail status

**Comment by brunitto** [comment]
Deploy trained engines, right?

**Comment by takabayashi** [comment]
Actually no because in the marvin environment we install two artifacts in server no build and no train is necessary and  the train action have to be done after the deploy.

1 - The engine - As example you can use the sample engine [sample-engine](https://github.com/marvin-ai/engines/tree/master/sample-engine)

2 - The executor engine - As example of a you can use this [executor package](https://s3.amazonaws.com/marvin-engine-executor/marvin-engine-executor-assembly-0.0.1.jar)

Yes...as a cli command (into the engine.py module) or as a make command (Makefile)... Take a look in the installation procedure just to get a clue.

If you want to generate a new engine, just use the `marvin engine-generate` and to rebuild from source the engine executor just use the `make package` command.

**Comment by takabayashi** [comment]
From a clean ubuntu installation like  (vagrant ubuntu/trusty64 VERSION="20170811.0.1") you need to install the following to have marvin toolbox running:

1. [Java 1.8](https://github.com/marvin-ai/marvin-vagrant-dev/blob/master/provision/java.sh)
2. [Python](https://github.com/marvin-ai/marvin-vagrant-dev/blob/master/provision/python.sh)
3. [Git Client](https://github.com/marvin-ai/marvin-vagrant-dev/blob/master/provision/git.sh)
4. `sudo apt-get install libsasl2-dev python-pip graphviz -y`
5. And follow the toolbox installation instructions [here](https://github.com/marvin-ai/marvin-python-toolbox/blob/master/README.md#common-installation-procedures) 

If you want is possible to use our [marvin-core vagrant](https://github.com/marvin-ai/marvin-vagrant-dev/blob/master/Vagrantfile#L40) to test the procedure bellow.

Any question, let me know!

**Comment by brunitto** [comment]
Cool, I was able to use these scripts to provision the production host. Some additional points to discuss:

1. The `fabfile.py` is duplicating some provisioning code from marvin-vagrant-dev, in the future, we might factor this code to a common provisioning scripts repo, so all stages (dev, staging and production for example) provisioning keep synced
2. I am installing marvin-engine-executor by cloning and making the package using the Makefile. Maybe it's a good idea to also "package" (or build) the python engine, so we deploy only the necessary code, as well as keeping multiple engine versions available in the hosts

Capistrano uses a cool directory structure for keeping multiple versions, we can use something like:

    /opt/marvin/engines/my-engine/
        current -> 1.0.0
        1.0.0/
        0.0.9/
        0.0.8/

So we can have the toolbox executing rollouts and rollbacks:

    marvin deploy --stage=production --version=1.0.0 --rollout
    marvin deploy --stage=staging --version=0.0.9 --rollback

**Comment by brunitto** [comment]
I am also working on Ubuntu-only compatible deploy for now.

**Comment by takabayashi** [comment]
ok

**Comment by takabayashi** [comment]
Done!
