### ISSUE TITLE
Update all Marvin dependencies and Engine dependencies and start to use >= instead of use ==

### ISSUE THREAD

**Issue by takabayashi** [marvin-ai/marvin-python-toolbox#102]

**Comment by gilbertoolimpio** [comment]
A newbie here! Can I get this one to help?

**Comment by rafaelnovello** [comment]
Hi @gilbertoolimpio, yes! Let us know if you gotta test the toolbox!

**Comment by takabayashi** [comment]
@gilbertoolimpio Are you going to do this task? We are planning the next version and this task is very  important.
