### ISSUE TITLE
Marvin Commands is not working properly

### ISSUE THREAD

**Issue by tiagofelipeandrade** [marvin-ai/marvin-python-toolbox#116]
I tried to use some basic commands (test, notebook) using version 0.0.4 toolbox, and it's not working.

1. Install new version of toolbox (v0.0.4)
2. Run marvin test
3. See error
4. Run marvin notebook
5. See error

**Screenshots**
<img width="1256" alt="terminal-marvin-errors" src="https://user-images.githubusercontent.com/12763777/43717588-693a698e-995e-11e8-9c5f-86977f00b49a.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Log [Error]

(python-toolbox-env) BRRJOBITAMM1522:~ tiago.andrade$ marvin test
Usage: marvin [OPTIONS] COMMAND [ARGS]...

Error: No such command "test".
(python-toolbox-env) BRRJOBITAMM1522:~ tiago.andrade$ marvin notebook
Usage: marvin [OPTIONS] COMMAND [ARGS]...

Error: No such command "notebook".

**Comment by rafaelnovello** [comment]
Hi @tiagofelipeandrade! Could you, pls, provide more infos about your environment?
1. What versions are you using? OS version, Python version?
2. Are you using virtualenv or virtualenvwrapper? What version?
3 Run `make clean` to clean your environment (be careful if you are not using virtialenv). After that, run `make marvin` and copy to us all the logs (you could do this with `make marvin > marvin.log`).

We'll test this new version on the same environment as yours but all this requested info will help us to understand the problem.

**Comment by rafaelnovello** [comment]
@tiagofelipeandrade, we have made some changes on toolbox commands list. To be clear, the toolbox should be used basically to generate new engines. Take a look at `marvin help` to see all commands available.

I believe there are some adjustments to be done on our documentations. Probably this is the reason you are running `marvin test` and `marvin notebook` on the toolbox. This commands will be available only in engines.

Let me know if you have success on creating a new engine and run the notebook on there.

**Comment by rafaelnovello** [comment]
@tiagofelipeandrade We will close this issue but you can re-open it if you have more problems.
Thanks for report!

**Comment by tiagofelipeandrade** [comment]
All set @rafaelnovello ! Thanks

![image](https://user-images.githubusercontent.com/12763777/43787861-6551ecb8-9a42-11e8-8ee2-8463bb4639ef.png)
