### ISSUE TITLE
Add code documentation to engine template

### ISSUE THREAD

**Issue by lucasbm88** [marvin-ai/marvin-python-toolbox#12]
The engine template should have code documentation indicating what should be coded in each phase of the project. i.e.: In the execute method of the acquisitor.py base file, a comment saying that the user should implement the logic for data acqusition and cleaning should be inputed.

**Comment by oldfly** [comment]
hi @lucasbm88 , i found the acquisitor_and_cleaner.py file in every engine template already has your execute method commented like:

def execute(self, **kwargs):
        """
        Setup the initial_dataset with all cleaned data necessary to build your dataset in the next action.

        Eg.

            self.initial_dataset = {...}
        """
        self.initial_dataset = {}

Is this issue already done by somebody, or you mean more detailed documentation?
