### ISSUE TITLE
Make compatible with python 3.X

### ISSUE THREAD

**Issue by takabayashi** [marvin-ai/marvin-python-toolbox#16]
The toolbox and the engine templates must be compatible with python 2.X and python 3.x. As technology decision we want to use the six library as general solution for that.

To do so we must change:

the toolbox code
the engine template code
the docker files
the vagrant files
the travis.xml
the README.md
Some references to the refactoring...

https://docs.python.org/3/howto/pyporting.html
https://media.readthedocs.org/pdf/six/latest/six.pdf
http://python3porting.com/noconv.html
https://wiki.python.org/moin/Python2orPython3

**Comment by oldfly** [comment]
Library Compatibility reference
https://pythonhosted.org/six/index.html
