### ISSUE TITLE
Jupyter notebook extension is not persisting status

### ISSUE THREAD

**Issue by lucasbm88** [marvin-ai/marvin-python-toolbox#34]
When marking DASFE cells using the jupyter notebook extension they are not continuing marked after refreshing the page.

Steps to reproduce:
 - Create a new project with marvin CLI
 - Start the notebook through the CLI
 - Create same cells and mark them in the DASFE textbox
 - Save the notebook (check that the code was generated in the folder)
 - Refresh (CTRL+R) the notebook browser window
 - Check that the cells are not marked anymore

**Comment by takabayashi** [comment]
fixed in 0.0.1 version
