### ISSUE TITLE
Message with gramatical error

### ISSUE THREAD

**Issue by jpfaria** [marvin-ai/marvin-python-toolbox#43]
[akka://MarvinExecutorSystem/user/pipelineActor] All artifacts from [evaluator] where saved with successful!! [ListBuffer(Done)]

**Comment by oldfly** [comment]
hey guys @jpfaria @lucasbm88 , i think this error belongs to marvin-engine-executor repository

**Comment by takabayashi** [comment]
Fixed in last version of engine-executor!
