### ISSUE TITLE
Change modifications from .bash_profile to .profile

### ISSUE THREAD

**Issue by marcossilva** [marvin-ai/marvin-python-toolbox#61]
I was wondering why I had to call `source ~/.bash_profile` everytime I opened a new terminal window and according to [this](https://askubuntu.com/questions/121073/why-bash-profile-is-not-getting-sourced-when-opening-a-terminal) post the bash_profile is not used on Ubuntu with the graphical enviroment, leading to the necessity to call it manually everytime. It might be a better option point the changes to the system enviroment to `.profile` file as the link states that it is called everytime a new window is opened.

**Comment by igor822** [comment]
You can force the `~/.bash_profile` load by adding the following command in `~/.bashrc` file

```bash
source ~/.bash_profile
```
And every time you open a new session, the `~/.bash_profile` will be loaded automatically
